### ISSUE TITLE
boston area commuter buses

### ISSUE THREAD

**Issue by aquaticpotato3677** [transitland/transitland-atlas#1011]
nearly all boston area commuter buses have been discontinued, including `f-drt-coachcompany`/`f-dr-coachcompany~ma~us`, `f-bloombus~ma~us`, and `f-drm-dattco`, as well as `f-drt0-limoliner~ma~us` and `f-drs-truenorthtransit~ma~us`, which are marked as historic but remain on transitland. what should be done about these? should they be removed or marked as historic?

**Comment by drewda** [comment]
A belated thanks for identifying which feeds/services no longer exist.

If an agency definitely doesn't offer service to the public anymore, deleting it from Atlas will remove it from all visible Transitland APIs. But the record is "soft deleted" within the Transitland database. In the future, we may add an extra option to the website and APIs to browse these soft-delete records.

But if an agency still exists but just doesn't have a current-feed, we're aiming their record in Atlas and available publicly in Transitland.
