### ISSUE TITLE
BART Departures Not Showing Up When Stop Name is Specified.

### ISSUE THREAD

**Issue by dinwun450** [transitland/transitland-atlas#1016]
When I entered a specific BART station ID in the departures API, I saw no departures in the departures key in the JSON request. Is the GTFS for BART departures broken?
![Screenshot 2024-02-12 181057](https://github.com/transitland/transitland-atlas/assets/42019518/c773cb05-a83a-4db7-87ed-63eae2700edd)

**Comment by drewda** [comment]
In the future, please post questions about Transitland APIs at https://github.com/transitland/transitland/discussions/categories/q-a 

Yes, our team detected some strange behavior in the BART static feed earlier today. Once the new import of https://www.transit.land/feeds/f-sf~bay~area~rg becomes active, this problem should be solved.
