### ISSUE TITLE
Banned IPs

### ISSUE THREAD

**Issue by Fale** [transitland/transitland-atlas#1033]
I see that `f-u0j-piemonte~autobus` results in a timeout. I know that it works on my machine, and I think that they banned transitland's IPs (probably due to "high traffic"). Would be possible to know which IPs are used by transitland so that we can see if we can get them unblocked? Thanks a lot!

**Comment by drewda** [comment]
Thank you for looking into this.

Yes, we've also noticed that we can download those feeds when we connect through a VPN.

Please email our team at hello@transit.land and we'll see if we can provide more information on relevant IP addresses.
