### ISSUE TITLE
Add Koleje Dolnośląskie (Poland)

### ISSUE THREAD

**Issue by etam** [transitland/transitland-atlas#1034]
See https://kolejedolnoslaskie.pl/rozklady-gtfs/

**Comment by drewda** [comment]
> The GTFS RT feed is also available but the site asks to e-mail for access. I assume it'll be password protected. How does transitland handle storing the passwords?

For the stack that runs transit.land, the Interline team maintains an internal list of credentials that are mapped onto individual feeds by Onestop ID or onto all of the feeds in a given DMFR file.

Other users of the Transitland Atlas repo may implement their own means of using their own credentials.
