### ISSUE TITLE
Update feeds/lillemetropole.fr.dmfr.json

### ISSUE THREAD

**Issue by matteoferrux** [transitland/transitland-atlas#1230]
The GTFS link for Ilevia (Lille Metropole) has changed recently.
The new link for GTFS is "https://media.ilevia.fr/opendata/gtfs.zip"

Moreover, the link for Open Data portal of Lille Metropole is now "https://data.lillemetropole.fr"

Source : https://transport.data.gouv.fr/datasets/localisation-des-arrets-ilevia-bus-metro-et-tram-gtfs-pictogrammes-du-reseau-ilevia-2

**Comment by drewda** [comment]
@matteoferrux thank you for sharing this update
