### ISSUE TITLE
Nassau Inter-County Exchange Transit Feed GTFS Issue

### ISSUE THREAD

**Issue by cmata23x3** [transitland/transitland-atlas#1352]
Hi,

I've noticed for [NICE](https://www.transit.land/feeds/f-dr5x-wwwnicebuscom) that their GTFS has not been fetched for quite some time. Their hosted GTFS url looks like it has some issues with their certificate even though the majority of the domain is able to use it fine. Is there a possibility to update the library used to make POST requests to support this endpoint? 

Chrome and other tools allow you to retrieve mixed content endpoints and just wanted to check if that was an option for Transit.land here.

**Comment by drewda** [comment]
Addressed via direct with NICE staff
