### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by rpedraza01** [transitland/transitland-atlas#246]
@drewda I'm trying to push changes to the TL repo from the command line. I've cloned the repo on my computer but I'm unable to push my changes. I get a message that says: 

`remote: Permission to transitland/transitland-atlas.git denied to rpedraza01.
fatal: unable to access 'https://github.com/transitland/transitland-atlas.git/': The requested URL returned error: 403`

Do I need to be granted some kind of access by you?

**Comment by drewda** [comment]
@rpedraza01 good question. Yes, you do need more permissions to be able to push changes directly into this repository. (We'd be glad to give you and Trillium permission in the future, but I think we should wait until you have practiced a bit more.)

You can "fork" the repository to create your own copy of the fork, create a branch in this copy, and then open a PR against this original repository.

I see some step-by-step instructions in https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/cloning-and-forking-repositories-from-github-desktop specifically where there is an option to select "To contribute to the parent project"

**Comment by rpedraza01** [comment]
@drewda I believe I got everything sorted out using the Github Desktop client. Check it out! https://github.com/transitland/transitland-atlas/pull/247

**Comment by drewda** [comment]
@rpedraza01 apologies for the delay, didn't see this earlier. Looks perfect!
