### ISSUE TITLE
operator models: a simpler representation inline with feed models

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-atlas#248]
There are currently multiple ways to associate one or more Feeds with an Operator. This can be confusing to contributors, who are unclear which is the most appropriate way to link Feeds and Operators.

Another problem is that the tlv2 sync scripts and queries are inconsistent in how they handle Operator groupings for GTFS-RT feeds.

We'll replace the separate Operator data model files (in `./operators`) with inline models/objects nested underneath each Feed model record.

**Comment by ericouyang** [comment]
@drewda - Do you have an update on this issue?

**Comment by irees** [comment]
@ericouyang I'm looking into this as I implement the updated operators schema

**Comment by drewda** [comment]
This overall issue has been addressed with https://github.com/transitland/transitland-atlas/pull/276

Open items remaining:
- [ ] update [DMFR JSON Schema](https://github.com/transitland/distributed-mobility-feed-registry/blob/master/json-schema/dmfr.schema-v0.3.0.json) to include the inline operators
- [ ] update [readme](https://github.com/transitland/transitland-atlas#operators) on operators

**Comment by drewda** [comment]
@ericouyang the Transitland website should now show working relationships between an operator's static and RT feeds. Let us know if you still see any examples of where this is not the case.

**Comment by drewda** [comment]
Documented in the readme at https://github.com/transitland/transitland-atlas#operators
