### ISSUE TITLE
Valley Retriever feed can be removed

### ISSUE THREAD

**Issue by christrillium** [transitland/transitland-atlas#37]
Valley Retriever (https://transit.land/feed-registry/operators/o-9rb-valleyretriever) went out of business.
https://www.bendbulletin.com/business/bend-newport-bus-service-ends/article_84768232-e9ed-549e-a335-5b0f656c2e5a.html

**Comment by drewda** [comment]
@christrillium thanks for reporting this, and for providing the context of the news article. We've removed it from the Transitland Atlas, which removes it from Transitland v2 and portions of Transitland v1.
