### ISSUE TITLE
HUT Airport Shuttle feed can be removed

### ISSUE THREAD

**Issue by christrillium** [transitland/transitland-atlas#38]
HUT was bought out by Groome Transportation, and no longer operates as a separate entity.
https://groometransportation.com/portland-airport/

**Comment by drewda** [comment]
Thanks for reporting this, @christrillium, and for the explanation.

We removed `f-9rb-hut~or~us` in https://github.com/transitland/transitland-atlas/pull/26 This change affects Transitland v2 (in development) but may not be apparent yet in the Transitland v1 Feed Registry.
