### ISSUE TITLE
Baker City Community Connection feed can be removed

### ISSUE THREAD

**Issue by christrillium** [transitland/transitland-atlas#39]
The Baker City Community Connection is a part of the overall Northeast Oregon Public Transit. It is no longer branded as a separate service, and is included in the http://oregon-gtfs.com/gtfs_data/northeast-or-us/northeast-or-us.zip feed.

**Comment by drewda** [comment]
`f-c2h-northeast~or~us` is set up properly

TODO: remove `o-9ru-bakercitycommunityconnection`
