### ISSUE TITLE
Mismatch between RT and static contents in govcbus.com.dmfr.json

### ISSUE THREAD

**Issue by mattlaquidara** [transitland/transitland-atlas#469]
The RT files referenced in [govcbus.com.dmfr.json](https://github.com/transitland/transitland-atlas/blame/master/feeds/govcbus.com.dmfr.json) contain data from several agencies that are not present in the Trillium-hosted static feed referenced in the same file. There is a GTFS static file hosted by govcbus.com that contains data from the agencies present in the RT feed available at https://govcbus.com/gtfs

I'd be happy to submit a pull request to change this file to use the govcbus GTFS static feed, but before I do so, I would like to ensure that the reference to other feed isn't intended. I didn't see anything in file's version history or closed issues that would indicate either way.

Thanks
-matt

**Comment by drewda** [comment]
Hi @mattlaquidara, thanks for noticing this. Associating the right static and RT feeds can indeed be complicated.

Let me follow up with our contacts at Trillium and we'll keep you posted.

**Comment by mattlaquidara** [comment]
Hi @drewda, any news on this front?

**Comment by drewda** [comment]
Yes, we have received some context from Trillium:

> Thank you for flagging this. Trillium maintains static GTFS for 7 of the 9 agencies included in GMV's GTFS-rt feed:
> 1. VCTC Intercity
> 2. Thousand Oaks
> 3. Simi Valley
> 4. Moorpark
> 5. Valley Express
> 6. Kanan Shuttle
> 7. Camarillo
> 
> We do not support
> 1. Ojai
> 2. Gold Coast
> 
> At this time, the Trillium static GTFS for those 7 agencies is the GTFS of record, but should an application require GTFS-rt integratity, the GMV static may be the better bet. We plan to have a resolution in 2022 for this, but in the meantime, I do not have an immediate recommendation on how to best describe this, as the GMV GTFS-rt feed is an aggregate of disparate agency datasets.

We will switch this over to the GMV source at https://govcbus.com/gtfs and be ready to switch back to Trillium's source in the future.

**Comment by drewda** [comment]
Hi @mattlaquidara, FYI, we are trying a new approach. The govcbus static feed should be available through Transitland APIs on the next import cycle. However, it will not be shown on the Transitland map or search results. Hopefully this will serve as an intermediate solution until we hear about changes from Trillium.

**Comment by mattlaquidara** [comment]
Works for me! thanks
