### ISSUE TITLE
Feed for Bratislava

### ISSUE THREAD

**Issue by NefrayLaysh** [transitland/transitland-atlas#579]
[opendata.bratislava.sk.dmfr.json](https://github.com/transitland/transitland-atlas/blob/master/feeds/opendata.bratislava.sk.dmfr.json)

Outdated

https://opendata.bratislava.sk/dataset/download/cestovny-poriadok-20220725/1 - here is link to updated feed

**Comment by drewda** [comment]
@NefrayLaysh thank you for this contribution.

Updated in #206
