### ISSUE TITLE
Data available in Transitland ?

### ISSUE THREAD

**Issue by adelcasse** [transitland/transitland-atlas#58]
On transitland feed registry, we can see : "The Feed Registry is now powered by Distributed Mobility Feed Registry files in the Transitland Atlas. Transitland Atlas is open to edits and additions from all on GitHub."

When we look at "SNCF" operator (https://transit.land/feed-registry/operators/o-u-sncf), data used is not accurate : we only have a specific region dataset (Pays de la Loire / PDL) instead of the national one.

But in this Transitland Atlas repository, the feed is right and points to the valid nation-wide regional trains dataset of SNCF : https://github.com/transitland/transitland-atlas/blob/master/feeds/data.sncf.com.dmfr.json

Isn't Transiland really synchronized with Transitland Atlas right now ? How to fix Transitland for this dataset ?

Best regards
Arnaud

**Comment by adelcasse** [comment]
Following my comment in pull request #43, should I propose a pull request to reset SNCF's feed for "TER" (https://github.com/transitland/transitland-atlas/blob/master/feeds/data.sncf.com.dmfr.json) to Onestop ID **f-u0-sncf\~tram\~train\~ter** to have a normal behavior and for SNCF data fix to be available in Transitland V1 ?

**Comment by drewda** [comment]
Hi @adelcasse, thank you for this issue report and for your patience. We previously migrated the source of truth for feeds to this repository. However, the source of truth for operators has continued to be in Transitland v1 production.

We are in the process of this migration now. The migration will either fully address your issue, or will put us all in a position to be able to fix it as a small follow-on.

**Comment by drewda** [comment]
Now that we have moved to the next stage of the migration, https://transit.land/feed-registry/operators/o-u-sncf now properly references `f-u0-sncf~ter` so I will close this issue.

Note that the contents of this feed are now available through Transitland v2, more parts of which will be public soon.

Thank you again for reporting this issue.
