### ISSUE TITLE
What's wrong with BART GTFS-realtime Feeds?

### ISSUE THREAD

**Issue by dinwun450** [transitland/transitland-atlas#945]
When I am compiling the real-time departures from the BART feeds, I only see the scheduled departures but haven't seen the real-time departures. Is the GTFSRT aspx file provided by BART broken or is it outdated?
ASPX file: https://api.bart.gov/gtfsrt/tripupdate.aspx

**Comment by drewda** [comment]
BART has been having some issues with RT since the release of their most recent schedule. See https://groups.google.com/g/511sfbaydeveloperresources/c/84yka_nlmI8

You could contact BART directly with any more questions: https://www.bart.gov/schedules/developers/devfeedback
